# Config Reference: https://github.com/foundry-rs/foundry/tree/master/config

[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
ffi = true
fs_permissions = [
  { access = "read", path = "./test/constants/trieAdd.json" },
  { access = "read", path = "./test/constants/trieOracle.json" },
]

[fmt]
bracket_spacing = true
